ssh_pubkey_temp: "{{ lookup('file', '../ssh/tmp_key.pub') }}"
keystodeploy:
  - name: Pierre
    sshkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOjVQkuv7RvSc1qiOiQDg/IJb6v6d7bHeXDvV/dH0U3L coimbrap@debian

ssh_kerberos_support: false
ssh_banner_path: '/etc/ssh/banner.txt'
ssh_banner: true
path_motd: '/etc/ssh/banner.txt'
ssh_permit_root_login: 'without-password'

ssh_host_key_files:
  - /etc/ssh/ssh_host_ed25519_key
  - /etc/ssh/ssh_host_rsa_key

ssh_macs:
  - hmac-sha2-256-etm@openssh.com
  - hmac-sha2-512-etm@openssh.com
  - umac-128-etm@openssh.com

ssh_ciphers:
  - chacha20-poly1305@openssh.com
  - aes256-gcm@openssh.com
  - aes128-gcm@openssh.com
  - aes256-ctr
  - aes192-ctr
  - aes128-ctr

ssh_host_key_algorithms:
  - ssh-ed25519
  - ssh-ed25519-cert-v01@openssh.com
  - rsa-sha2-256
  - rsa-sha2-512
  - rsa-sha2-256-cert-v01@openssh.com
  - rsa-sha2-512-cert-v01@openssh.com

ssh_kex:
  - curve25519-sha256
  - curve25519-sha256@libssh.org
  - diffie-hellman-group14-sha256
  - diffie-hellman-group16-sha512
  - diffie-hellman-group18-sha512
  - diffie-hellman-group-exchange-sha256
