- name: sshkeys
  src: git+https://github.com/coimbrap/ansible-role-sshkeys
  version: 'v0.2'
- name: openvswitch
  src: git+https://github.com/coimbrap/ansible-role-openvswitch
  version: 'v0.1'
- name: ufw
  src: git+https://github.com/coimbrap/ansible-role-ufw
  version: 'v4.2.1'
- name: apt-cacher-ng
  src: git+https://github.com/coimbrap/ansible-role-apt-cacher
  version: 'v0.1'
- name: squid3
  src: git+https://github.com/coimbrap/ansible-role-squid3
  version: 'v1.1'
- name: proxmox-init
  src: git+https://github.com/coimbrap/ansible-role-proxmox-init
  version: 'v0.2'
- name: motd
  src: git+https://github.com/coimbrap/ansible-role-motd
  version: 'v0.1'
- name: letsencrypt
  src: git+https://github.com/coimbrap/ansible-role-letsencrypt-ovh
  version: 'v0.1'
- name: ferm
  src: git+https://github.com/coimbrap/ansible-role-ferm
  version: 'v0.1'
- name: createvm
  src: git+https://github.com/coimbrap/ansible-role-create-vm
  version: 'v0.2'
- name: createct
  src: git+https://github.com/coimbrap/ansible-role-create-ct
  version: 'v0.5'
- name: haproxy
  src: git+https://github.com/coimbrap/ansible-role-haproxy
  version: 'v7.0'
- name: selfsignedcerts
  src: git+https://github.com/coimbrap/ansible-role-self-signed-certs
  version: 'v0.2'
- name: ssh_hardening
  src: git+https://github.com/dev-sec/ansible-ssh-hardening
  version: '9.7.0'
- name: opnsense
  src: git+https://github.com/coimbrap/ansible-role-opnsense
  version: 'v1.5'
- name: bind
  src: git+https://github.com/coimbrap/ansible-role-bind
  version: 'v0.1'
