---
base_domain: devo.re
haproxy_global_dhparams: false

haproxy_defaults_logformat: '"%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r"'
frontend_with_acl: secure-all

haproxy_frontend:
  - name: unsecure-all
    mode: http
    bind:
      - listen: ':::80'
        param:
          - v4v6
    redirect:
      - string: 'scheme https code 301'
    acl:
      - string: 'www hdr_beg(host) -i www.'
    reqirep:
      - search: '^Host:\ www.(.*)$ Host:\'
        string: '\1'
        cond: 'if www'
    reqadd:
      - string: 'X-Forwarded-Proto:\ https'
    default_backend: drop-http

  - name: secure-all
    mode: http
    option:
      - forwardfor
    bind:
      - listen: ':::443'
        param:
          - v4v6
          - ssl
          - no-sslv3
          - crt /etc/ssl/letsencrypt
        option:
          - forwardfor
          - httplog
    rspadd:
      - string: 'Strict-Transport-Security:\ max-age=63072000'
    acl:
      - string: 'www hdr_beg(host) -i www.'
      - string: 'web hdr_end(host) devo.re'
    reqirep:
      - search: '^Host:\ www.(.*)$ Host:\'
        string: '\1'
        cond: 'if www'
    default_backend: drop-http

haproxy_backend:
  - name: drop-http
    mode: http
    http-request:
      - action: deny

backendacl:
  - name: bitwarden
    sub: p
    ipPorts: ['10.0.20.102:80']
  - name: cloud
    sub: c
    ipPorts: ['10.0.20.108:443']
    opt: ssl verify none
  - name: ldapui
    sub: lui
    ipPorts: ['10.0.20.107:80']
    #opt: ssl check ca-file /etc/ssl/haproxy/devore-ca.pem
  - name: mailgateway
    sub: mgw
    ipPorts: ['10.0.20.103:8006']
    opt: ssl verify none
  - name: pve-interface
    sub: pve
    ipPorts: ['10.0.20.1:8006']
    opt: ssl verify none
  - name: opn-interface
    sub: opn
    ipPorts: ['10.0.20.254:443']
    opt: ssl verify none
