ct_name: mailgw
ct_vmid: "103"
ct_node: "pve"
ct_if: vmbr1
ct_vlan: 20
ct_cpus: 1
ct_ram: 1024
ct_prefix4: "10.0.20"
ct_swap: 0
ct_storage: local-zfs
ct_disk: "8"
ct_template: local:vztmpl/proxmox-mailgateway-6.3-standard_6.3-1_amd64.tar.gz
ct_onboot: 1
ct_gw4_suffix: "254"
node_bastion: bastion
connect_to_proxy: false
