keystodeploy:
  - name: Pierre
    sshkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOjVQkuv7RvSc1qiOiQDg/IJb6v6d7bHeXDvV/dH0U3L
  - name: Samuel B.
    sshkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDdVWUpl3k6v4mo/B7lu7DSpj5oBIZZePmnFyElRds5E
