- hosts: fw
  gather_facts: false
  vars:
    opn_unset:
      - filter
      - interfaces
      - vlans
      - nat
      - bridges
      - dhcpd
      - gateways
      - dhcpdv6
      - dhrelay
      - dhcrelay6
  vars_prompt:
    - name: ansible_ssh_pass
      prompt: Enter password for OPNsense
      private: no
  roles:
    - opnsense
