- hosts: pmg
  gather_facts: false
  roles:
    - createct
  vars:
    ssh_access: false
  tasks:
  - name: install python
    raw: 'sudo apt-get -y install python3 python3-apt'

- hosts: pmg
  gather_facts: true
  roles:
    - pmg-init
    - createct
    - ssh_hardening
