ct_name: bastion
ct_vmid: "100"
ct_node: "pve"
ct_if: vmbr1
ct_vlan: 20
ct_prefix4: "10.0.20"
ct_cpus: 1
ct_ram: 510
ct_swap: 0
ct_storage: local-zfs
ct_disk: 4
ct_template: local:vztmpl/debian-10-standard_10.7-1_amd64.tar.gz
ct_onboot: 1
ct_unprivileged: 1
ct_gw4_suffix: "254"
ssh_banner: false
path_motd: '/etc/motd'
ssh_print_motd: true
erase_ssh: true
#node_bastion: pve
ssh_ip: "devo.re"
